apiVersion: v2
appVersion: v9.7
description: A Helm chart for XL Deploy
name: xl-deploy-helmcharts
version: 1.0.2-GA

dependencies:

- name: postgresql
  version: 9.8.5
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install

- name: rabbitmq-ha
  version: 1.47.0
  repository: "https://charts.helm.sh/stable"
  condition: rabbitmq-ha.install
