apiVersion: v2
appVersion: v10.0
description: A Helm chart for XL Deploy
name: xl-deploy-oc-helmcharts
version: 1.2.1

dependencies:

- name: postgresql
  version: 9.8.5
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install

- name: rabbitmq
  version: 8.6.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: rabbitmq.install
